/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/testimonials/testimonials.component';
const styles_TestimonialsComponent:any[] = ([] as any[]);
export const RenderType_TestimonialsComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_TestimonialsComponent,data:{}});
export function View_TestimonialsComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',[['class',
      'underConstruction']],(null as any),(null as any),(null as any),(null as any),
      (null as any)))],(null as any),(null as any));
}
export function View_TestimonialsComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'testimonials',
      ([] as any[]),(null as any),(null as any),(null as any),View_TestimonialsComponent_0,
      RenderType_TestimonialsComponent)),i0.ɵdid(49152,(null as any),0,i1.TestimonialsComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const TestimonialsComponentNgFactory:i0.ComponentFactory<i1.TestimonialsComponent> = i0.ɵccf('testimonials',
    i1.TestimonialsComponent,View_TestimonialsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL3Rlc3RpbW9uaWFscy90ZXN0aW1vbmlhbHMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0ZyZWVMYW5jaW5nL3ByYXlhcy9hcHBsaWNhdGlvbi9zcmMvd2ViQXBwL2FwcC90ZXN0aW1vbmlhbHMvdGVzdGltb25pYWxzLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0ZyZWVMYW5jaW5nL3ByYXlhcy9hcHBsaWNhdGlvbi9zcmMvd2ViQXBwL2FwcC90ZXN0aW1vbmlhbHMvdGVzdGltb25pYWxzLmNvbXBvbmVudC50cy5UZXN0aW1vbmlhbHNDb21wb25lbnQuaHRtbCIsIm5nOi8vL0Q6L0ZyZWVMYW5jaW5nL3ByYXlhcy9hcHBsaWNhdGlvbi9zcmMvd2ViQXBwL2FwcC90ZXN0aW1vbmlhbHMvdGVzdGltb25pYWxzLmNvbXBvbmVudC50cy5UZXN0aW1vbmlhbHNDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwidW5kZXJDb25zdHJ1Y3Rpb25cIj48L2Rpdj4iLCI8dGVzdGltb25pYWxzPjwvdGVzdGltb25pYWxzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQTs7O29CQ0FBO01BQUE7c0NBQUEsVUFBQTtNQUFBOzs7In0=
