/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../app/app.module';
import * as i2 from '../../app/app.component';
import * as i3 from './home-component/home.component.ngfactory';
import * as i4 from './about-us/about-us.component.ngfactory';
import * as i5 from './gallery/gallery.component.ngfactory';
import * as i6 from './testimonials/testimonials.component.ngfactory';
import * as i7 from './contact-us/contact-us.component.ngfactory';
import * as i8 from './app.component.ngfactory';
import * as i9 from '@angular/common';
import * as i10 from '@angular/platform-browser';
import * as i11 from '@angular/animations/browser';
import * as i12 from '@angular/platform-browser/animations';
import * as i13 from '@angular/animations';
import * as i14 from '@angular/router';
import * as i15 from '../../app/home-component/home.component';
import * as i16 from '../../app/about-us/about-us.component';
import * as i17 from '../../app/gallery/gallery.component';
import * as i18 from '../../app/testimonials/testimonials.component';
import * as i19 from '../../app/contact-us/contact-us.component';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.HomeComponentNgFactory,i4.AboutUsComponentNgFactory,i5.GalleryComponentNgFactory,
              i6.TestimonialsComponentNgFactory,i7.ContactUsComponentNgFactory,i8.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i9.NgLocalization,i9.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i10.DomSanitizer,i10.ɵe,[i9.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i10.DomSanitizer]),i0.ɵmpd(4608,
              i10.HAMMER_GESTURE_CONFIG,i10.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i10.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i10.ɵDomEventsPlugin(p0_0),new i10.ɵKeyEventsPlugin(p1_0),
                    new i10.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i9.DOCUMENT,i9.DOCUMENT,i9.DOCUMENT,i10.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i10.EventManager,i10.EventManager,[i10.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i10.ɵDomSharedStylesHost,i10.ɵDomSharedStylesHost,[i9.DOCUMENT]),
          i0.ɵmpd(4608,i10.ɵDomRendererFactory2,i10.ɵDomRendererFactory2,[i10.EventManager,
              i10.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i11.AnimationDriver,i12.ɵc,([] as any[])),
          i0.ɵmpd(5120,i11.ɵAnimationStyleNormalizer,i12.ɵd,([] as any[])),i0.ɵmpd(4608,
              i11.ɵAnimationEngine,i12.ɵb,[i11.AnimationDriver,i11.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i12.ɵe,[i10.ɵDomRendererFactory2,i11.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(6144,i10.ɵSharedStylesHost,(null as any),[i10.ɵDomSharedStylesHost]),
          i0.ɵmpd(4608,i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i10.Meta,
              i10.Meta,[i9.DOCUMENT]),i0.ɵmpd(4608,i10.Title,i10.Title,[i9.DOCUMENT]),
          i0.ɵmpd(4608,i13.AnimationBuilder,i12.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(5120,i14.ActivatedRoute,i14.ɵf,[i14.Router]),i0.ɵmpd(4608,i14.NoPreloading,
              i14.NoPreloading,([] as any[])),i0.ɵmpd(6144,i14.PreloadingStrategy,
              (null as any),[i14.NoPreloading]),i0.ɵmpd(135680,i14.RouterPreloader,
              i14.RouterPreloader,[i14.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i14.PreloadingStrategy]),i0.ɵmpd(4608,i14.PreloadAllModules,
              i14.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i14.ROUTER_INITIALIZER,
              i14.ɵi,[i14.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i14.ROUTER_INITIALIZER]),i0.ɵmpd(512,i9.CommonModule,i9.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i10.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i14.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i14.ɵg,i14.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i10.ɵc(p0_0,p0_1),i14.ɵh(p1_0)];
              },[[2,i10.NgProbeToken],[2,i0.NgProbeToken],i14.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i10.BrowserModule,i10.BrowserModule,[[3,i10.BrowserModule]]),
          i0.ɵmpd(1024,i14.ɵa,i14.ɵd,[[3,i14.Router]]),i0.ɵmpd(512,i14.UrlSerializer,
              i14.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i14.ChildrenOutletContexts,
              i14.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i14.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i9.LocationStrategy,i14.ɵc,[i9.PlatformLocation,
              [2,i9.APP_BASE_HREF],i14.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i9.Location,
              i9.Location,[i9.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i14.ROUTES,
              () => {
                return [[{path:'',pathMatch:'full',redirectTo:'/home'},{path:'home',
                    component:i15.HomeComponent},{path:'aboutUs',component:i16.AboutUsComponent},
                    {path:'gallery',component:i17.GalleryComponent},{path:'testimonials',
                        component:i18.TestimonialsComponent},{path:'contact',component:i19.ContactUsComponent}]];
              },([] as any[])),i0.ɵmpd(1024,i14.Router,i14.ɵe,[i0.ApplicationRef,i14.UrlSerializer,
              i14.ChildrenOutletContexts,i9.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i14.ROUTES,i14.ROUTER_CONFIGURATION,[2,i14.UrlHandlingStrategy],
              [2,i14.RouteReuseStrategy]]),i0.ɵmpd(512,i14.RouterModule,i14.RouterModule,
              [[2,i14.ɵa],[2,i14.Router]]),i0.ɵmpd(512,i12.BrowserAnimationsModule,
              i12.BrowserAnimationsModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,
              i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
