/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/contact-us/contact-us.component';
const styles_ContactUsComponent:any[] = ([] as any[]);
export const RenderType_ContactUsComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ContactUsComponent,data:{}});
export function View_ContactUsComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',[['class',
      'underConstruction']],(null as any),(null as any),(null as any),(null as any),
      (null as any)))],(null as any),(null as any));
}
export function View_ContactUsComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'Contact-Us',([] as any[]),
      (null as any),(null as any),(null as any),View_ContactUsComponent_0,RenderType_ContactUsComponent)),
      i0.ɵdid(49152,(null as any),0,i1.ContactUsComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const ContactUsComponentNgFactory:i0.ComponentFactory<i1.ContactUsComponent> = i0.ɵccf('Contact-Us',
    i1.ContactUsComponent,View_ContactUsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL2NvbnRhY3QtdXMvY29udGFjdC11cy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL2NvbnRhY3QtdXMvY29udGFjdC11cy5jb21wb25lbnQudHMiLCJuZzovLy9EOi9GcmVlTGFuY2luZy9wcmF5YXMvYXBwbGljYXRpb24vc3JjL3dlYkFwcC9hcHAvY29udGFjdC11cy9jb250YWN0LXVzLmNvbXBvbmVudC50cy5Db250YWN0VXNDb21wb25lbnQuaHRtbCIsIm5nOi8vL0Q6L0ZyZWVMYW5jaW5nL3ByYXlhcy9hcHBsaWNhdGlvbi9zcmMvd2ViQXBwL2FwcC9jb250YWN0LXVzL2NvbnRhY3QtdXMuY29tcG9uZW50LnRzLkNvbnRhY3RVc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJ1bmRlckNvbnN0cnVjdGlvblwiPjwvZGl2PiIsIjxDb250YWN0LVVzPjwvQ29udGFjdC1Vcz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQUE7OztvQkNBQTtNQUFBO2FBQUE7VUFBQTs7OyJ9
