/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/gallery/gallery.component';
const styles_GalleryComponent:any[] = ([] as any[]);
export const RenderType_GalleryComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_GalleryComponent,data:{}});
export function View_GalleryComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',[['class',
      'underConstruction']],(null as any),(null as any),(null as any),(null as any),
      (null as any)))],(null as any),(null as any));
}
export function View_GalleryComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'gallery',([] as any[]),
      (null as any),(null as any),(null as any),View_GalleryComponent_0,RenderType_GalleryComponent)),
      i0.ɵdid(49152,(null as any),0,i1.GalleryComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const GalleryComponentNgFactory:i0.ComponentFactory<i1.GalleryComponent> = i0.ɵccf('gallery',
    i1.GalleryComponent,View_GalleryComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL2dhbGxlcnkvZ2FsbGVyeS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL2dhbGxlcnkvZ2FsbGVyeS5jb21wb25lbnQudHMiLCJuZzovLy9EOi9GcmVlTGFuY2luZy9wcmF5YXMvYXBwbGljYXRpb24vc3JjL3dlYkFwcC9hcHAvZ2FsbGVyeS9nYWxsZXJ5LmNvbXBvbmVudC50cy5HYWxsZXJ5Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9GcmVlTGFuY2luZy9wcmF5YXMvYXBwbGljYXRpb24vc3JjL3dlYkFwcC9hcHAvZ2FsbGVyeS9nYWxsZXJ5LmNvbXBvbmVudC50cy5HYWxsZXJ5Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cInVuZGVyQ29uc3RydWN0aW9uXCI+PC9kaXY+IiwiPGdhbGxlcnk+PC9nYWxsZXJ5PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQTs7O29CQ0FBO01BQUE7YUFBQTtVQUFBOzs7In0=
