/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.gallery-view[_ngcontent-%COMP%] {\r\n    padding:5%;\r\n    \r\n}\r\n\r\n.gal-image-folder[_ngcontent-%COMP%] {\r\n    position: relative;\r\n    float: left;\r\n    height: 40vh;\r\n    width: 21%;\r\n    display: block;\r\n    background: white;\r\n    margin:0% 2% 2%;\r\n    border-radius: 10px;\r\n    box-shadow: 0px 3px 6px 0px grey;\r\n    cursor: pointer;\r\n}\r\n\r\n.gal-image-folder[_ngcontent-%COMP%]:nth-child(4n) {\r\n  margin-right: 0;\r\n}\r\n\r\n.gal-img[_ngcontent-%COMP%] > img[_ngcontent-%COMP%] {\r\n    width: 100%;\r\n    min-height: 32vh;\r\n    border-radius: 0px 0px 10px 10px;\r\n    box-shadow: 0px 3px 6px 0px grey;\r\n}\r\n\r\n.gal-img-desc[_ngcontent-%COMP%] {\r\n    font-family: \'Artifika\', serif;\r\n    font-size: 14px;\r\n    height: 10%;\r\n    text-align: center;\r\n    color: teal;\r\n    padding: 5px 2px;\r\n}\r\n\r\n@media screen and (max-width: 736px) {\r\n    .gal-image-folder[_ngcontent-%COMP%] {\r\n        width: 96%;\r\n        height: 80vh;\r\n        margin-bottom:10vh;\r\n    }\r\n\r\n    .gal-image-folder[_ngcontent-%COMP%]:nth-child(4n) {\r\n        margin-right: 2%;\r\n    }\r\n\r\n    .gal-img[_ngcontent-%COMP%] > img[_ngcontent-%COMP%] {\r\n        height: 70vh;\r\n    }\r\n    .enlarge-image[_ngcontent-%COMP%] {\r\n        display: none;\r\n    }\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL2dhbGxlcnkvZ2FsbGVyeS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0ZyZWVMYW5jaW5nL3ByYXlhcy9hcHBsaWNhdGlvbi9zcmMvd2ViQXBwL2FwcC9nYWxsZXJ5L2dhbGxlcnkuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
