/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './gallery.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from '../../../app/gallery/gallery.component';
const styles_GalleryComponent:any[] = [i0.styles];
export const RenderType_GalleryComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_GalleryComponent,data:{}});
function View_GalleryComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),12,'div',[['class',
      'gal-image-folder']],[[1,'id',0]],(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵeld(0,
      (null as any),(null as any),3,'div',[['class','gal-img']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n            '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),0,'img',([] as any[]),[[8,'src',
          4]],(null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n        '])),(_l()(),i1.ɵted((null as any),['\n         '])),(_l()(),
          i1.ɵeld(0,(null as any),(null as any),4,'div',[['class','gal-img-desc']],
              (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n            '])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),1,'span',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['',''])),(_l()(),
          i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵted((null as any),['\n    ']))],
      (null as any),(_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = (('gal-img-' + _v.context.index) + 1);
        _ck(_v,0,0,currVal_0);
        const currVal_1:any = (_co.ref + _v.context.$implicit.file);
        _ck(_v,4,0,currVal_1);
        const currVal_2:any = _v.context.$implicit.description;
        _ck(_v,10,0,currVal_2);
      });
}
export function View_GalleryComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'gallery-view']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_GalleryComponent_1)),i1.ɵdid(802816,(null as any),
          0,i2.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],{ngForOf:[0,
              'ngForOf']},(null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,
      _v) => {
    var _co:i3.GalleryComponent = _v.component;
    const currVal_0:any = _co.gallery;
    _ck(_v,3,0,currVal_0);
  },(null as any));
}
export function View_GalleryComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'gallery',([] as any[]),
      (null as any),(null as any),(null as any),View_GalleryComponent_0,RenderType_GalleryComponent)),
      i1.ɵdid(49152,(null as any),0,i3.GalleryComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const GalleryComponentNgFactory:i1.ComponentFactory<i3.GalleryComponent> = i1.ɵccf('gallery',
    i3.GalleryComponent,View_GalleryComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL2dhbGxlcnkvZ2FsbGVyeS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL2dhbGxlcnkvZ2FsbGVyeS5jb21wb25lbnQudHMiLCJuZzovLy9EOi9GcmVlTGFuY2luZy9wcmF5YXMvYXBwbGljYXRpb24vc3JjL3dlYkFwcC9hcHAvZ2FsbGVyeS9nYWxsZXJ5LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL2dhbGxlcnkvZ2FsbGVyeS5jb21wb25lbnQudHMuR2FsbGVyeUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJnYWxsZXJ5LXZpZXdcIj5cclxuICAgIDxkaXYgKm5nRm9yPVwibGV0IGltYWdlIG9mIGdhbGxlcnk7IGxldCBpID0gaW5kZXhcIiBbYXR0ci5pZF09XCInZ2FsLWltZy0nICsgaSArIDFcIiBjbGFzcz1cImdhbC1pbWFnZS1mb2xkZXJcIj5cclxuICAgICAgICA8ZGl2IGNsYXNzPVwiZ2FsLWltZ1wiPlxyXG4gICAgICAgICAgICA8aW1nIFtzcmNdPVwicmVmICsgaW1hZ2UuZmlsZVwiPlxyXG4gICAgICAgIDwvZGl2PlxyXG4gICAgICAgICA8ZGl2IGNsYXNzPVwiZ2FsLWltZy1kZXNjXCI+XHJcbiAgICAgICAgICAgIDxzcGFuPnt7aW1hZ2UuZGVzY3JpcHRpb259fTwvc3Bhbj5cclxuICAgICAgICA8L2Rpdj5cclxuICAgIDwvZGl2PlxyXG48L2Rpdj4iLCI8Z2FsbGVyeT48L2dhbGxlcnk+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNDSTtNQUFBO01BQUEsZ0JBQTBHLCtDQUN0RztNQUFBO01BQUEsNENBQXFCO01BQ2pCO1VBQUEsOERBQThCO1VBQUEsaUJBQzVCLGdEQUNMO2lCQUFBO2NBQUE7TUFBMEIsbURBQ3ZCO1VBQUE7VUFBQSw4QkFBTSx3Q0FBNEI7aUJBQUEsZ0NBQ2hDOzs7UUFOd0M7UUFBbEQsV0FBa0QsU0FBbEQ7UUFFYTtRQUFMLFdBQUssU0FBTDtRQUdNO1FBQUE7Ozs7b0JBTmxCO01BQUE7TUFBMEIsMkNBQ3RCO1VBQUEsK0RBQUE7VUFBQTtjQUFBLDJCQU9NOzs7SUFQRDtJQUFMLFdBQUssU0FBTDs7OztvQkNESjtNQUFBO2FBQUE7VUFBQTs7OyJ9
