/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['.footer[_ngcontent-%COMP%]{\r\n    display: block;\r\n    height:30px;\r\n    background-color: #373737;\r\n    opacity: 0.8;\r\n    padding:5px;\r\n}\r\n\r\n.footer[_ngcontent-%COMP%] > p[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n    color:white;\r\n}'];
//# sourceMappingURL=footer.component.css.shim.ngstyle.js.map