/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './footer.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../app/footer/footer.component';
const styles_FooterComponent:any[] = [i0.styles];
export const RenderType_FooterComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_FooterComponent,data:{}});
export function View_FooterComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'footer']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['Copyright Prayash, 2017'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_FooterComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'prayash-footer',
      ([] as any[]),(null as any),(null as any),(null as any),View_FooterComponent_0,
      RenderType_FooterComponent)),i1.ɵdid(49152,(null as any),0,i2.FooterComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const FooterComponentNgFactory:i1.ComponentFactory<i2.FooterComponent> = i1.ɵccf('prayash-footer',
    i2.FooterComponent,View_FooterComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL2Zvb3Rlci9mb290ZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0ZyZWVMYW5jaW5nL3ByYXlhcy9hcHBsaWNhdGlvbi9zcmMvd2ViQXBwL2FwcC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0ZyZWVMYW5jaW5nL3ByYXlhcy9hcHBsaWNhdGlvbi9zcmMvd2ViQXBwL2FwcC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovRnJlZUxhbmNpbmcvcHJheWFzL2FwcGxpY2F0aW9uL3NyYy93ZWJBcHAvYXBwL2Zvb3Rlci9mb290ZXIuY29tcG9uZW50LnRzLkZvb3RlckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJmb290ZXJcIj5cclxuICAgIDxwPkNvcHlyaWdodCBQcmF5YXNoLCAyMDE3PC9wPlxyXG48L2Rpdj4iLCI8cHJheWFzaC1mb290ZXI+PC9wcmF5YXNoLWZvb3Rlcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFvQiwyQ0FDaEI7VUFBQTtVQUFBLGdCQUFHO01BQTJCOzs7b0JDRGxDO01BQUE7Z0NBQUEsVUFBQTtNQUFBOzs7In0=
